#!/usr/bin/env python3
"""
Falcon — generate a scrolling-checkerboard Motion-JPEG frame set for the
ESP32 OV519/OV530 (Xbox Video Camera) emulator.

The OV519 bridge's on-chip JPEG engine streams baseline MJPEG at 320x240. For
Milestone 1 we do not run a JPEG encoder on the ESP32; instead we pre-encode a
short loop of scrolling-checkerboard frames here and cycle them at runtime to
show motion. Each frame is a complete baseline JPEG (DQT+DHT included) so any
decoder -- a v4l2 viewer over gspca_ov519, or the Xbox-side picojpeg -- can
decode it standalone.

Output: a C header with each frame as a byte array plus a {data,len} table.

Usage:
    python tools/gen_checkerboard_jpegs.py \
        --out main/checkerboard_jpegs.h [--frames 16] [--square 40] \
        [--quality 75] [--dump-dir out_jpegs]
"""
import argparse
import os
from PIL import Image

W, H = 320, 240


def make_frame(phase, frames, square):
    """A checkerboard shifted by `phase/frames` of one square, so the pattern
    scrolls smoothly and loops seamlessly over the whole set."""
    shift = int(round(phase * (2 * square) / frames))  # 2*square = one full period
    img = Image.new("RGB", (W, H))
    px = img.load()
    for y in range(H):
        for x in range(W):
            cx = ((x + shift) // square) & 1
            cy = (y // square) & 1
            on = cx ^ cy
            # Distinct, saturated-ish colors so it's obvious on screen and the
            # luma spread is wide (helps prove a real decode).
            px[x, y] = (230, 210, 40) if on else (30, 60, 200)
    return img


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="output C header path")
    ap.add_argument("--frames", type=int, default=16)
    ap.add_argument("--square", type=int, default=40)
    ap.add_argument("--quality", type=int, default=75)
    ap.add_argument("--dump-dir", default=None, help="also write .jpg files here")
    args = ap.parse_args()

    if args.dump_dir:
        os.makedirs(args.dump_dir, exist_ok=True)

    blobs = []
    for p in range(args.frames):
        img = make_frame(p, args.frames, args.square)
        import io
        buf = io.BytesIO()
        # baseline (progressive=False), 4:2:2 subsampling to match the OV519's
        # YH2V1 scan; complete tables so it decodes standalone.
        img.save(buf, format="JPEG", quality=args.quality,
                 progressive=False, subsampling="4:2:2", optimize=False)
        data = buf.getvalue()
        assert data[:4] == b"\xff\xd8\xff\xe0", "expected JFIF baseline SOI/APP0"
        blobs.append(data)
        if args.dump_dir:
            with open(os.path.join(args.dump_dir, f"cb_{p:02d}.jpg"), "wb") as f:
                f.write(data)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", newline="\n") as f:
        f.write("// Generated by tools/gen_checkerboard_jpegs.py -- do not edit.\n")
        f.write("// Scrolling-checkerboard baseline-MJPEG frames for the Falcon\n")
        f.write("// OV519/OV530 (Xbox Video Camera) emulator.\n")
        f.write("#pragma once\n#include <stddef.h>\n\n")
        f.write(f"#define CHECKERBOARD_W {W}\n")
        f.write(f"#define CHECKERBOARD_H {H}\n")
        f.write(f"#define CHECKERBOARD_FRAME_COUNT {len(blobs)}\n\n")
        for i, data in enumerate(blobs):
            f.write(f"static const unsigned char cb_frame_{i}[] = {{\n")
            for j in range(0, len(data), 16):
                row = ", ".join(f"0x{b:02x}" for b in data[j:j + 16])
                f.write(f"    {row},\n")
            f.write("};\n")
        f.write("\nstatic const struct { const unsigned char *data; unsigned int len; } "
                "cb_frames[CHECKERBOARD_FRAME_COUNT] = {\n")
        for i in range(len(blobs)):
            f.write(f"    {{ cb_frame_{i}, (unsigned int)sizeof(cb_frame_{i}) }},\n")
        f.write("};\n")

    sizes = [len(b) for b in blobs]
    print(f"wrote {args.out}: {len(blobs)} frames, "
          f"sizes {min(sizes)}-{max(sizes)} B (avg {sum(sizes)//len(sizes)} B), "
          f"total {sum(sizes)} B")


if __name__ == "__main__":
    main()
